# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blobs < Formula
  desc "Self-hosted browser for S3-compatible blob storage (R2, AWS, Minio, B2)"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/blobs/v0.1.0/blobs_0.1.0_macos_x86_64.tar.gz"
      sha256 "6e46a2bb44180f6f91fcc7a674dbcef042b7927413bf92554fc7feede4c56e96"

      define_method(:install) do
        bin.install "blobs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/blobs/v0.1.0/blobs_0.1.0_macos_arm64.tar.gz"
      sha256 "b4484d8e3530220389cbd3bb2093a91e92a1f948fd9c09ffe49bdd7602da184c"

      define_method(:install) do
        bin.install "blobs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/blobs/v0.1.0/blobs_0.1.0_linux_x86_64.tar.gz"
      sha256 "d41c9ed8ce727512d78fb7e076398a9dae070760e0bd609ccda788f82eaabecf"
      define_method(:install) do
        bin.install "blobs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/blobs/v0.1.0/blobs_0.1.0_linux_arm64.tar.gz"
      sha256 "da4945f5d108fb826d5759f6bb10f75f87842b3d4e35530c7d4d711cf0806dc7"
      define_method(:install) do
        bin.install "blobs"
      end
    end
  end
end
