# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bookmarks < Formula
  desc "Self-hosted link saver with categories and JSON API"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/bookmarks/v0.2.0/bookmarks_0.2.0_macos_x86_64.tar.gz"
      sha256 "9499b600e2c4309636743e9aed06422d6fff42b6e54701e71ac20163a15cc2e5"

      define_method(:install) do
        bin.install "bookmarks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/bookmarks/v0.2.0/bookmarks_0.2.0_macos_arm64.tar.gz"
      sha256 "d33ccd26e1183db5241030435e7863432f4e12fb76af8a39091d528e490c7290"

      define_method(:install) do
        bin.install "bookmarks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/bookmarks/v0.2.0/bookmarks_0.2.0_linux_x86_64.tar.gz"
      sha256 "75d4cc22e4dc956a39b4492b15dfb297dc61c60d9794a806bd5023e236e5b475"
      define_method(:install) do
        bin.install "bookmarks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/bookmarks/v0.2.0/bookmarks_0.2.0_linux_arm64.tar.gz"
      sha256 "86ca7e8815cc5c00cdbef620d58516eb5b159850c20950f7fe2b250d9ff251c4"
      define_method(:install) do
        bin.install "bookmarks"
      end
    end
  end
end
