# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cellar < Formula
  desc "Self-hosted wine tracker"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/cellar/v0.3.0/cellar_0.3.0_macos_x86_64.tar.gz"
      sha256 "8a27ed73c1c326cf2b7f6d4b23a2a7b93ac44ee0cdee2970388cd4dc1812b6f0"

      define_method(:install) do
        bin.install "cellar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/cellar/v0.3.0/cellar_0.3.0_macos_arm64.tar.gz"
      sha256 "aeb59ae0dc885214e65c315af9b5dd8b35b1fc195acf5ef81ad1cb052f35413f"

      define_method(:install) do
        bin.install "cellar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/cellar/v0.3.0/cellar_0.3.0_linux_x86_64.tar.gz"
      sha256 "c6fd6c419ff593de4d48fc634fe7edb0f2c8085378ab524a47a992e124766253"
      define_method(:install) do
        bin.install "cellar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/cellar/v0.3.0/cellar_0.3.0_linux_arm64.tar.gz"
      sha256 "48d13d5ceef64177d89cc3657b8a88659069ec755adc438584af165b4525a61f"
      define_method(:install) do
        bin.install "cellar"
      end
    end
  end
end
