# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Easel < Formula
  desc "Daily public-domain painting viewer"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/easel/v0.1.0/easel_0.1.0_macos_x86_64.tar.gz"
      sha256 "79dd4c3b6e5eaf488d8f621c1d87e9eea30b583e382dd1b08a76bdc3799a5fce"

      define_method(:install) do
        bin.install "easel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/easel/v0.1.0/easel_0.1.0_macos_arm64.tar.gz"
      sha256 "3b6c2abc4109ccd72cfa66834923badc8e248fd5e3a533a2d9f307d1f17daca3"

      define_method(:install) do
        bin.install "easel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/easel/v0.1.0/easel_0.1.0_linux_x86_64.tar.gz"
      sha256 "fd122eee4c7665a18e1de199e803fd89d8d0c904c439cf9533b699ba2c750cfe"
      define_method(:install) do
        bin.install "easel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/easel/v0.1.0/easel_0.1.0_linux_arm64.tar.gz"
      sha256 "7e6332038858a71cbb0d30fd0d9d9c8a2ee7e888b4f2c49f467597ee30edfcd5"
      define_method(:install) do
        bin.install "easel"
      end
    end
  end
end
