# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Feeds < Formula
  desc "Self-hosted RSS reader with background polling"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/feeds/v0.4.0/feeds_0.4.0_macos_x86_64.tar.gz"
      sha256 "3ee46ad84939b46790faa734379a0625522616b7c52107c52770c3d031af6267"

      define_method(:install) do
        bin.install "feeds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/feeds/v0.4.0/feeds_0.4.0_macos_arm64.tar.gz"
      sha256 "146c2e17cfe38d23d074704f0545673be9a7763533dd209e63380509546d73f7"

      define_method(:install) do
        bin.install "feeds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/feeds/v0.4.0/feeds_0.4.0_linux_x86_64.tar.gz"
      sha256 "7cabc4c6ff97f4528892bd95befec4e85f85913168619bc9e003ac6dcbfd8cf4"
      define_method(:install) do
        bin.install "feeds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/feeds/v0.4.0/feeds_0.4.0_linux_arm64.tar.gz"
      sha256 "ba45807d44a703abb41446a1a518b4ed77dfb524ecd6a775bedeed282f8e4260"
      define_method(:install) do
        bin.install "feeds"
      end
    end
  end
end
