# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jotts < Formula
  desc "Self-hosted markdown notes app"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/jotts/v0.3.0/jotts_0.3.0_macos_x86_64.tar.gz"
      sha256 "aa501c11b9867445f9947578269a42aa9ccb884e13f1d84c4cdf9a24dd354812"

      define_method(:install) do
        bin.install "jotts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/jotts/v0.3.0/jotts_0.3.0_macos_arm64.tar.gz"
      sha256 "bab93035bc86fb790963b18e47f55b425ae7a6d80e3432c06ea09190d36489ba"

      define_method(:install) do
        bin.install "jotts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/jotts/v0.3.0/jotts_0.3.0_linux_x86_64.tar.gz"
      sha256 "18dcb81af2d28eec91cbb09d24c5e50bcd948e299bdfea47c99effad635c363f"
      define_method(:install) do
        bin.install "jotts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/jotts/v0.3.0/jotts_0.3.0_linux_arm64.tar.gz"
      sha256 "85725386193b887464a7b86c4a4e7a18cd11cabbca87ef9a0fec3ec0d8267e76"
      define_method(:install) do
        bin.install "jotts"
      end
    end
  end
end
