# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Library < Formula
  desc "Self-hosted book tracker with Google Books search"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/library/v0.2.0/library_0.2.0_macos_x86_64.tar.gz"
      sha256 "89191a3c70460d04b7790f7a480c53e9fd45d8c91a846d71de42236c44c55245"

      define_method(:install) do
        bin.install "library"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/library/v0.2.0/library_0.2.0_macos_arm64.tar.gz"
      sha256 "204cfcc411b8fe22e51f90883a8dfa261f43d6ed2fd7df820350551569859ba2"

      define_method(:install) do
        bin.install "library"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/library/v0.2.0/library_0.2.0_linux_x86_64.tar.gz"
      sha256 "3002642a600fb2400567b0dcd52c0408b75b92ffb839399b2b4a2106ccb0d733"
      define_method(:install) do
        bin.install "library"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/library/v0.2.0/library_0.2.0_linux_arm64.tar.gz"
      sha256 "103a758065ec3ae9f8b369286e84ac7b8afdd9be50ca658a9de2db2d937b459e"
      define_method(:install) do
        bin.install "library"
      end
    end
  end
end
