# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Og < Formula
  desc "Open Graph inspector"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/og/v0.2.0/og_0.2.0_macos_x86_64.tar.gz"
      sha256 "97f364ffded769e51a2dd552cf240c53563cbf8d818877b82c80164d6d8e521c"

      define_method(:install) do
        bin.install "og"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/og/v0.2.0/og_0.2.0_macos_arm64.tar.gz"
      sha256 "ec048e0f870b2d858a3d482461ea6d022d667afbb8b70c44319d226224907a11"

      define_method(:install) do
        bin.install "og"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/og/v0.2.0/og_0.2.0_linux_x86_64.tar.gz"
      sha256 "83c4b6b5bac01c5582dcc0bb9aeea5a58b467e8bc8df98dd0dffb1123b1b5f16"
      define_method(:install) do
        bin.install "og"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/og/v0.2.0/og_0.2.0_linux_arm64.tar.gz"
      sha256 "c9c4ca96afc26143054736feec7430edc30d43a1b2d5ad6a002672db0bff5ddf"
      define_method(:install) do
        bin.install "og"
      end
    end
  end
end
