# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Posts < Formula
  desc "Self-hosted blog CMS with local or R2 storage"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/posts/v0.3.0/posts_0.3.0_macos_x86_64.tar.gz"
      sha256 "1ad6c49df016ad6a7c8d2a7eeb68dd352c4bb8ed3a9ed6c42509889536e5323a"

      define_method(:install) do
        bin.install "posts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/posts/v0.3.0/posts_0.3.0_macos_arm64.tar.gz"
      sha256 "c20ad566db538f2a1f92b5d4fb44dbdca09057a1ef045d8928576d2ca90d3acf"

      define_method(:install) do
        bin.install "posts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/posts/v0.3.0/posts_0.3.0_linux_x86_64.tar.gz"
      sha256 "73bba14c6ae30cf528a1ab0ce121e81b4657c8fe715201e971ff8d3dec024808"
      define_method(:install) do
        bin.install "posts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/posts/v0.3.0/posts_0.3.0_linux_arm64.tar.gz"
      sha256 "186aaf7f5c3b0d4499d2fd68141dd9853b8a26455e96b124b8398be12167a08f"
      define_method(:install) do
        bin.install "posts"
      end
    end
  end
end
