# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shrink < Formula
  desc "Image compression tool, EXIF preserved, GPS stripped"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/shrink/v0.2.0/shrink_0.2.0_macos_x86_64.tar.gz"
      sha256 "4575dc1bcd17567ec69d072ef57ff895c60ac6cf176f7be5d51bbc3017414566"

      define_method(:install) do
        bin.install "shrink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/shrink/v0.2.0/shrink_0.2.0_macos_arm64.tar.gz"
      sha256 "f7eca56d12f3c46297f87b88564b356d309590b9c898f554694139c8ac5f1f56"

      define_method(:install) do
        bin.install "shrink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/shrink/v0.2.0/shrink_0.2.0_linux_x86_64.tar.gz"
      sha256 "88602eb074e930d66c75c66325bf23729ad1225538c4b1f42bfb4a7d8e8b7b4d"
      define_method(:install) do
        bin.install "shrink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/shrink/v0.2.0/shrink_0.2.0_linux_arm64.tar.gz"
      sha256 "44e2febaf0c124484959e9ef3898e9a9ea8e1f3853644bd79afdc4864dc59788"
      define_method(:install) do
        bin.install "shrink"
      end
    end
  end
end
