# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sipp < Formula
  desc "Code sharing CLI, server, and TUI"
  homepage "https://github.com/stevedylandev/andromeda"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevedylandev/andromeda/releases/download/sipp/v0.3.0/sipp_0.3.0_macos_x86_64.tar.gz"
      sha256 "0baa55e27f6d7a7beed7f9f4dc669a9231c8bd83f0753bbdf399fa47608396a7"

      define_method(:install) do
        bin.install "sipp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevedylandev/andromeda/releases/download/sipp/v0.3.0/sipp_0.3.0_macos_arm64.tar.gz"
      sha256 "98320dfe9b7648cd65c7a48939dd80725288ab56172ebb099fac654973d030f7"

      define_method(:install) do
        bin.install "sipp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/sipp/v0.3.0/sipp_0.3.0_linux_x86_64.tar.gz"
      sha256 "d4fa37e8869f5532dd61316486e1257cb291eaa8f101f500d4e58746cd15ac15"
      define_method(:install) do
        bin.install "sipp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevedylandev/andromeda/releases/download/sipp/v0.3.0/sipp_0.3.0_linux_arm64.tar.gz"
      sha256 "e13873e5ea71b8da04bf0b8b1bcddd660622f08be6f7cf393ce58fafa8e595e2"
      define_method(:install) do
        bin.install "sipp"
      end
    end
  end

  test do
    system "#{bin}/sipp", "--help"
  end
end
